// Import/export: native JSON project files, whole-library backups, and self-describing
// AI-handoff Markdown at three depth levels. Pure functions — no DOM, no app state mutation.
import { TYPES, TYPE_ORDER, EDGE_KINDS, SCHEMA, VERSION } from './state.js';
import { uid, slugify } from './ui.js';

export const PROJECT_FORMAT = 'agentmap/project@1';
export const BACKUP_FORMAT = 'agentmap/backup@1';
const APP = `AgentMap ${VERSION}`;

/* ════════════════════════ exports ════════════════════════ */

export function exportProjectFile(p) {
  const payload = { format: PROJECT_FORMAT, app: APP, exportedAt: new Date().toISOString(), project: p };
  return { filename: `${slugify(p.name)}.agentmap.json`, text: JSON.stringify(payload, null, 2) };
}

export function exportBackupFile(projects) {
  const payload = { format: BACKUP_FORMAT, app: APP, exportedAt: new Date().toISOString(), projects };
  const d = new Date().toISOString().slice(0, 10);
  return { filename: `agentmap-backup-${d}.json`, text: JSON.stringify(payload, null, 2) };
}

/* ════════════════════════ AI handoff ════════════════════════ */

const LANGS = {
  ts: 'typescript', tsx: 'tsx', js: 'javascript', jsx: 'jsx', mjs: 'javascript', py: 'python',
  sh: 'bash', bash: 'bash', json: 'json', yml: 'yaml', yaml: 'yaml', md: 'markdown', html: 'html',
  css: 'css', sql: 'sql', go: 'go', rs: 'rust', rb: 'ruby', java: 'java', toml: 'toml',
};
const langFor = (node) => LANGS[(node.path || '').split('.').pop()?.toLowerCase()] || '';

function fenced(content, lang = '') {
  let run = 2;
  for (const m of String(content).matchAll(/`+/g)) run = Math.max(run, m[0].length);
  const f = '`'.repeat(Math.max(3, run + 1));
  return `${f}${lang}\n${content}\n${f}`;
}

const typeLabel = (t) => (TYPES[t] || TYPES.other).label;
const inline = (s) => String(s ?? '').replace(/\s+/g, ' ').trim();

const edgeText = (e, titleOf) => {
  const note = e.label ? ` — “${inline(e.label)}”` : '';
  if (e.kind === 'callback') return `${titleOf(e.from)} ⇢ ${titleOf(e.to)} _(callback)_${note}`;
  if (e.kind === 'relation') return `${titleOf(e.from)} ↔ ${titleOf(e.to)} _(relation)_${note}`;
  return `${titleOf(e.from)} → ${titleOf(e.to)}${note}`;
};

export function buildHandoff(p, depth = 'standard') {
  const nodes = p.nodes;
  const byId = new Map(nodes.map((n) => [n.id, n]));
  const kids = new Map([['root', []]]);
  for (const n of nodes) {
    const key = byId.has(n.parentId) ? n.parentId : 'root';
    if (!kids.has(key)) kids.set(key, []);
    kids.get(key).push(n);
  }
  for (const list of kids.values()) list.sort((a, b) => (a.x - b.x) || (a.y - b.y));
  const childrenOf = (id) => kids.get(id) || [];

  const layerEdges = (pid) => {
    const inLayer = new Set(childrenOf(pid).map((n) => n.id));
    return p.edges.filter((e) => inLayer.has(e.from) && inLayer.has(e.to));
  };
  const pathTo = (n) => {
    const parts = [];
    let cur = n;
    const guard = new Set();
    while (cur && !guard.has(cur.id)) {
      guard.add(cur.id);
      parts.unshift(cur.title || 'Untitled');
      cur = byId.get(cur.parentId);
    }
    return parts.join(' ▸ ');
  };
  const layerName = (pid) => (pid === 'root' ? 'Top level' : pathTo(byId.get(pid)));

  const degree = new Map(nodes.map((n) => [n.id, { in: 0, out: 0 }]));
  for (const e of p.edges) {
    if (degree.has(e.from)) degree.get(e.from).out++;
    if (degree.has(e.to)) degree.get(e.to).in++;
  }

  const byType = {};
  for (const t of TYPE_ORDER) byType[t] = nodes.filter((n) => (TYPES[n.type] ? n.type : 'other') === t).length;
  const containers = nodes.filter((n) => childrenOf(n.id).length > 0);
  let maxDepth = 1;
  {
    const walk = (pid, d) => {
      for (const n of childrenOf(pid)) { maxDepth = Math.max(maxDepth, d); walk(n.id, d + 1); }
    };
    walk('root', 1);
  }

  const md = [];
  const push = (...lines) => md.push(...lines);
  const depthName = { overview: 'Overview', standard: 'Standard', full: 'Full detail' }[depth] || 'Standard';

  /* header + reading guide (the self-describing part) */
  push(
    `# ${p.name} — AI agent workflow map`,
    '',
    `> **What this document is.** A self-describing export of a visual workflow map built in AgentMap. It describes an AI-agent system as a layered node graph: **nodes** are the system's components, **nesting** shows containment (a component with an inner sub-map), and **connections** are directed links between components. Everything after "How to read this map" is the project itself.`,
    '',
    `- Export depth: **${depthName}**${depth === 'overview' ? ' (architecture only — no per-component detail or file contents)' : depth === 'standard' ? ' (architecture + per-component metadata; file contents omitted)' : ' (architecture + per-component metadata + full file contents)'}`,
    `- Exported: ${new Date().toISOString()} · Generated by ${APP}`,
    `- Size: **${nodes.length} components** across **${maxDepth} ${maxDepth === 1 ? 'level' : 'levels'}**, **${p.edges.length} connections**, ${containers.length} container${containers.length === 1 ? '' : 's'}`,
    depth === 'overview'
      ? `- Re-import: this Overview export is prose-only and **cannot** be re-imported. Use a Standard/Full export or the .json project file to restore the map.`
      : `- Re-import: the fenced JSON block at the end of this file ("Machine-readable project data") restores the exact map in AgentMap (Library → Import).`,
    '',
    '## How to read this map',
    '',
    '| Type | Meaning |',
    '| --- | --- |',
    '| Phase | A stage of the overall workflow (the top-level flow usually reads left to right) |',
    '| Agent | An autonomous AI worker with its own instructions |',
    '| Skill | A reusable capability, prompt module, or tool wrapper |',
    '| Hook | An automation trigger or guardrail that runs at a defined moment |',
    '| Code | A source file or script |',
    '| Documentation | Reference material, policies, schemas, or templates |',
    '| Other | Anything that does not fit the categories above |',
    '',
    'Connections come in three kinds: `A → B` is **flow** (A feeds into, precedes, or triggers B), `A ⇢ B (callback)` means A returns or reports back to B (a response leg, usually closing a loop), and `A ↔ B (relation)` is a non-directional association. A quoted note after a connection is its author-written trigger/description. Components marked **(contains N)** have an internal sub-map listed under "Full hierarchy". Connections are scoped to the level where they are drawn: top-level arrows describe the macro flow; arrows inside a container describe its internal mechanics. `path`, `tags`, and summaries are author-written metadata.',
    '',
  );

  if (p.description) push('## Project description', '', p.description, '');

  /* system overview */
  const typeCounts = TYPE_ORDER.filter((t) => byType[t] > 0).map((t) => `${byType[t]} ${typeLabel(t).toLowerCase()}${byType[t] === 1 ? '' : 's'}`).join(' · ');
  const rootNodes = childrenOf('root');
  const rootEdges = layerEdges('root');
  const rootIn = new Map(rootNodes.map((n) => [n.id, 0]));
  const rootOut = new Map(rootNodes.map((n) => [n.id, 0]));
  for (const e of rootEdges) {
    if (e.kind === 'relation') continue; // associations don't make something an entry/exit
    rootIn.set(e.to, rootIn.get(e.to) + 1);
    rootOut.set(e.from, rootOut.get(e.from) + 1);
  }
  const entries = rootNodes.filter((n) => rootIn.get(n.id) === 0 && rootOut.get(n.id) > 0);
  const exits = rootNodes.filter((n) => rootOut.get(n.id) === 0 && rootIn.get(n.id) > 0);

  push('## System overview', '', `Component mix: ${typeCounts || 'empty project'}.`);
  if (entries.length) push(`Entry points (top level): ${entries.map((n) => `**${n.title}**`).join(', ')}.`);
  if (exits.length) push(`End points (top level): ${exits.map((n) => `**${n.title}**`).join(', ')}.`);
  push('');

  /* top-level architecture */
  push('## Top-level architecture', '');
  for (const n of rootNodes) {
    const cc = childrenOf(n.id).length;
    push(`- **${n.title}** \`${typeLabel(n.type)}\`${cc ? ` (contains ${cc})` : ''}${n.summary ? ` — ${inline(n.summary)}` : ''}`);
  }
  if (rootEdges.length) {
    push('', 'Top-level flow:', '');
    for (const e of rootEdges) push(`- ${edgeText(e, (nid) => byId.get(nid).title)}`);
  }
  push('');

  /* full hierarchy */
  push('## Full hierarchy', '');
  const tree = (pid, indent) => {
    for (const n of childrenOf(pid)) {
      const cc = childrenOf(n.id).length;
      push(`${'  '.repeat(indent)}- **${n.title}** \`${typeLabel(n.type)}\`${n.path ? ` — \`${n.path}\`` : ''}${cc ? ` (contains ${cc})` : ''}`);
      tree(n.id, indent + 1);
    }
  };
  tree('root', 0);
  push('');

  /* key components */
  const scored = nodes.map((n) => {
    const d = degree.get(n.id);
    const cc = childrenOf(n.id).length;
    return { n, score: d.in + d.out + cc * 1.5, d, cc };
  }).filter((s) => s.score >= 2).sort((a, b) => b.score - a.score).slice(0, 6);
  if (scored.length) {
    push('## Most important components', '', 'Ranked by how connected and how structural each component is:', '');
    for (const { n, d, cc } of scored) {
      const why = [d.in ? `${d.in} in` : '', d.out ? `${d.out} out` : '', cc ? `${cc} inside` : ''].filter(Boolean).join(', ');
      push(`- **${pathTo(n)}** \`${typeLabel(n.type)}\` (${why})${n.summary ? ` — ${inline(n.summary)}` : ''}`);
    }
    push('');
  }

  /* per-component detail (standard + full) */
  if (depth !== 'overview') {
    push('## Components by layer', '');
    const layers = ['root', ...nodes.filter((n) => childrenOf(n.id).length).map((n) => n.id)];
    const emitted = new Set();
    const emitLayer = (pid) => {
      if (emitted.has(pid)) return;
      emitted.add(pid);
      const list = childrenOf(pid);
      if (!list.length) return;
      push(`### Layer: ${layerName(pid)}`, '');
      for (const n of list) {
        const cc = childrenOf(n.id).length;
        push(`#### ${n.title} \`${typeLabel(n.type)}\``);
        const meta = [];
        if (n.path) meta.push(`- Path: \`${n.path}\``);
        if (n.tags?.length) meta.push(`- Tags: ${n.tags.map((t) => `\`${t}\``).join(' ')}`);
        if (cc) meta.push(`- Contains: ${childrenOf(n.id).map((c) => `**${c.title}**`).join(', ')}`);
        if (meta.length) push(...meta);
        if (n.summary) push('', inline(n.summary));
        push('');
      }
      const le = layerEdges(pid);
      if (le.length) {
        push('Connections in this layer:', '');
        for (const e of le) push(`- ${edgeText(e, (nid) => byId.get(nid).title)}`);
        push('');
      }
    };
    for (const pid of layers) emitLayer(pid);
  }

  /* full contents */
  if (depth === 'full') {
    push('## Component contents', '', 'Full stored content of every component that has any.', '');
    const walk = (pid) => {
      for (const n of childrenOf(pid)) {
        if (n.content && n.content.trim()) {
          push(`### ${pathTo(n)}${n.path ? ` — \`${n.path}\`` : ''}`, '', fenced(n.content, langFor(n)), '');
        }
        walk(n.id);
      }
    };
    walk('root');
  }

  /* embedded machine-readable data */
  if (depth !== 'overview') {
    push(
      '## Machine-readable project data',
      '',
      'The fenced JSON below is the complete project in AgentMap\'s native format — including node positions, layers, and full content. Importing this .md file into AgentMap restores the exact map. AI systems can also parse it directly for precise structure.',
      '',
      fenced(JSON.stringify({ format: PROJECT_FORMAT, app: APP, exportedAt: new Date().toISOString(), project: p }, null, 2), 'json'),
      '',
    );
  }

  const text = md.join('\n');
  return { filename: `${slugify(p.name)}-handoff-${depth}.md`, text };
}

/* ════════════════════════ import ════════════════════════ */

export function parseImportText(text, filename = 'file') {
  let obj = null;
  try { obj = JSON.parse(text); } catch { /* maybe markdown */ }

  if (!obj) {
    obj = extractEmbeddedJSON(text);
    if (!obj) {
      if (/^#|```/m.test(text)) {
        throw new Error(`“${filename}” has no embedded AgentMap data. Overview handoffs are prose-only — import a Standard/Full handoff or a .agentmap.json file instead.`);
      }
      throw new Error(`“${filename}” isn't an AgentMap export (expected a .agentmap.json project, a backup, or a Standard/Full handoff .md).`);
    }
  }

  if (obj && typeof obj === 'object' && obj.format === BACKUP_FORMAT) {
    const list = Array.isArray(obj.projects) ? obj.projects : [];
    if (!list.length) throw new Error(`“${filename}” is an AgentMap backup, but it contains no projects.`);
    const projects = [];
    const warnings = [];
    list.forEach((raw, i) => {
      const r = normalizeProject(raw);
      projects.push(r.project);
      warnings.push(...r.warnings.map((w) => `${r.project.name}: ${w}`));
    });
    return { kind: 'backup', projects, warnings };
  }

  const raw = obj?.format === PROJECT_FORMAT ? obj.project : obj;
  const warnings = [];
  if (obj?.format !== PROJECT_FORMAT) {
    if (!raw || typeof raw !== 'object' || (!Array.isArray(raw.nodes) && typeof raw.nodes !== 'object')) {
      throw new Error(`“${filename}” isn't an AgentMap export (no recognizable project data inside).`);
    }
    warnings.push('File was missing the AgentMap wrapper — imported best-effort.');
  }
  const r = normalizeProject(raw);
  return { kind: 'project', projects: [r.project], warnings: [...warnings, ...r.warnings] };
}

function extractEmbeddedJSON(text) {
  const re = /(`{3,})json[^\n]*\n([\s\S]*?)\n\1/g;
  let m;
  while ((m = re.exec(text))) {
    try {
      const obj = JSON.parse(m[2]);
      if (obj && typeof obj.format === 'string' && obj.format.startsWith('agentmap/')) return obj;
    } catch { /* try next block */ }
  }
  return null;
}

export function normalizeProject(raw) {
  const warnings = [];
  const warn = (s) => warnings.push(s);
  if (!raw || typeof raw !== 'object') throw new Error('Project data is not an object.');

  const str = (v, fb = '') => (typeof v === 'string' ? v : fb);
  const validISO = (v) => (typeof v === 'string' && Number.isFinite(new Date(v).getTime()));
  const now = new Date().toISOString();

  const p = {
    id: str(raw.id) || uid(),
    schema: Number.isFinite(raw.schema) ? raw.schema : SCHEMA,
    name: str(raw.name).trim() || 'Imported project',
    description: str(raw.description),
    createdAt: validISO(raw.createdAt) ? raw.createdAt : now,
    updatedAt: validISO(raw.updatedAt) ? raw.updatedAt : now,
    settings: { snap: raw.settings?.snap !== false },
    lastParent: str(raw.lastParent, 'root') || 'root',
    views: {},
    nodes: [],
    edges: [],
  };
  if (p.schema > SCHEMA) warn(`Made by a newer AgentMap (schema ${p.schema}) — imported best-effort.`);

  /* nodes: accept array or {id: node} map */
  let rawNodes = Array.isArray(raw.nodes) ? raw.nodes : (raw.nodes && typeof raw.nodes === 'object' ? Object.values(raw.nodes) : []);
  const seen = new Set();
  let unplaced = 0;
  for (const rn of rawNodes) {
    if (!rn || typeof rn !== 'object') { warn('Skipped a malformed node entry.'); continue; }
    let nid = str(rn.id);
    if (!nid) { nid = uid(); warn(`Node “${str(rn.title, 'Untitled')}” had no id — assigned one.`); }
    if (seen.has(nid)) { warn(`Skipped duplicate node id “${nid}”.`); continue; }
    seen.add(nid);
    let type = str(rn.type, 'other');
    if (!TYPES[type]) { if (rn.type !== undefined) warn(`Unknown type “${type}” on “${str(rn.title, 'Untitled')}” → Other.`); type = 'other'; }
    const num = (v) => (typeof v === 'number' && Number.isFinite(v) ? v : null);
    let x = num(rn.x), y = num(rn.y);
    if (x === null || y === null) {
      x = 60 + (unplaced % 5) * 252;
      y = 60 + Math.floor(unplaced / 5) * 144;
      unplaced++;
    }
    p.nodes.push({
      id: nid,
      parentId: str(rn.parentId, 'root') || 'root',
      type,
      title: str(rn.title) || 'Untitled',
      path: str(rn.path),
      tags: Array.isArray(rn.tags) ? rn.tags.map((t) => String(t)).filter(Boolean).slice(0, 24) : [],
      summary: str(rn.summary),
      content: str(rn.content),
      x, y,
    });
  }
  if (unplaced) warn(`${unplaced} node${unplaced === 1 ? ' was' : 's were'} missing a position — placed automatically.`);

  /* parent integrity + cycle breaking */
  const ids = new Set(p.nodes.map((n) => n.id));
  for (const n of p.nodes) {
    if (n.parentId !== 'root' && !ids.has(n.parentId)) {
      warn(`“${n.title}” pointed at a missing container — moved to the top level.`);
      n.parentId = 'root';
    }
    if (n.parentId === n.id) { warn(`“${n.title}” was its own container — moved to the top level.`); n.parentId = 'root'; }
  }
  for (const n of p.nodes) {
    const visited = new Set([n.id]);
    let cur = n;
    while (cur.parentId !== 'root') {
      if (visited.has(cur.parentId)) {
        warn(`Broke a containment cycle at “${cur.title}”.`);
        cur.parentId = 'root';
        break;
      }
      visited.add(cur.parentId);
      cur = p.nodes.find((m) => m.id === cur.parentId);
      if (!cur) break;
    }
  }

  /* edges */
  const parentOf = new Map(p.nodes.map((n) => [n.id, n.parentId]));
  const seenEdge = new Set();
  const rawEdges = Array.isArray(raw.edges) ? raw.edges : [];
  let dropped = 0;
  for (const re of rawEdges) {
    if (!re || typeof re !== 'object') { dropped++; continue; }
    const from = str(re.from), to = str(re.to);
    if (!ids.has(from) || !ids.has(to) || from === to) { dropped++; continue; }
    if (parentOf.get(from) !== parentOf.get(to)) { dropped++; continue; }
    const key = from + '→' + to;
    if (seenEdge.has(key)) { dropped++; continue; }
    seenEdge.add(key);
    const edge = { id: str(re.id) || uid(), from, to };
    const kind = str(re.kind);
    if (kind && kind !== 'flow') {
      if (EDGE_KINDS[kind]) edge.kind = kind;
      else warn(`Unknown connection kind "${kind}" → flow.`);
    }
    const label = str(re.label).trim().slice(0, 140);
    if (label) edge.label = label;
    if (Array.isArray(re.points)) {
      const pts = re.points
        .filter((pt) => pt && Number.isFinite(pt.x) && Number.isFinite(pt.y))
        .slice(0, 32)
        .map((pt) => ({ x: Math.round(pt.x), y: Math.round(pt.y) }));
      if (pts.length) edge.points = pts;
    }
    p.edges.push(edge);
  }
  if (dropped) warn(`Dropped ${dropped} invalid connection${dropped === 1 ? '' : 's'} (missing endpoints, duplicates, or cross-layer).`);

  /* views + lastParent */
  if (raw.views && typeof raw.views === 'object') {
    for (const [k, v] of Object.entries(raw.views)) {
      if ((k === 'root' || ids.has(k)) && v && Number.isFinite(v.x) && Number.isFinite(v.y) && Number.isFinite(v.z)) {
        p.views[k] = { x: v.x, y: v.y, z: v.z };
      }
    }
  }
  if (p.lastParent !== 'root' && !ids.has(p.lastParent)) p.lastParent = 'root';

  return { project: p, warnings };
}
